name: Weather API Workflow

on:
  push:
    branches:
      - main

jobs:
  get_weather:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install requests
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Get Weather
        run: |
          python your_script.py  # Replace with the path to your script
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
